spring:
  ai:
    ollama:
      embedding:
        options:
          model: bge-m3:latest
      chat:
        options:
          model: qwen3:32b # gpt-oss:120b
#          temperature: 0.8
#          numPredict: 16000
#          topP: 0.95
#          topK: 100
#          repeatPenalty: 0.9
#          numCtx: 32768
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-doc
    username: admin
    password: admin
