spring:
  ai:
    ollama:
      embedding:
        options:
          model: embeddinggemma:300m
      chat:
        options:
          model: qwen3:8b

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-doc
    username: admin
    password: admin
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
